### ISSUE TITLE
Erase this repository- you are not allowed to use my CODE

### ISSUE THREAD

**Issue by AleksandarHaber** [lolbuoy/ML-RL#1]
You are not allowed to use this code - read the license. Bring down this repository immediately!

**Comment by lolbuoy** [comment]
Hey Alexander, this is just for a college assignment. I hope you don't mind
it.

**Comment by AleksandarHaber** [comment]
You erase the code immediately, you are not allowed to repost it or use it.

**Comment by lolbuoy** [comment]
Okay, I'll take it down.

**Comment by AleksandarHaber** [comment]
You still did not erase the codes that you copy-pasted from the website and from the original repository. You have 24 hours to take down the code before we will fill-in a DMCA complaint. Also, we will take further legal actions.

**Comment by lolbuoy** [comment]
Yes I'm doing it, i am stuck in a place without network

**Comment by lolbuoy** [comment]
Tbf I've added your website a source on the branch. Either ways i will
erase it.

**Comment by lolbuoy** [comment]
@AleksandarHaber check it now, all the conflicting codes have been removed.

**Comment by AleksandarHaber** [comment]
Erase all the branches and erase all the codes that you used from our
website! This is our message. You have 24 hours to remove and erase all the
branches and all the codes that you posted without our permission!
