### ISSUE TITLE
ERASE all the branches with our code

### ISSUE THREAD

**Issue by AleksandarHaber** [lolbuoy/ML-RL#2]
Erase all the branches and erase all the codes that you used from our website! This is our message. You have 24 hours to remove and erase all the branches and all the codes that you posted without our permission!

**Comment by lolbuoy** [comment]
Codes are removed what else is the issue

**Comment by lolbuoy** [comment]
If anything else needs to be fixed let me know @AleksandarHaber

**Comment by lolbuoy** [comment]
Else I'm closing this issue
